/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.ahung.ymir;

import driver.Driver;
import org.testng.annotations.*;

public class LibraryTest extends Driver {
    @Test
    public void runChromeDriver() {
        goToPage("http://www.google.com");
    }
}
